// Lean 4 exporter for the typed RML fragment (issue #60).
//
// The exporter is deliberately separate from evaluation: it translates
// declaration syntax into a Lean-checkable artifact and rejects probabilistic
// forms instead of assigning them a Lean meaning.

import {
  Diagnostic,
  RmlError,
  isNum,
  keyOf,
  parseBinding,
  readLinoForms,
} from './rml-links.mjs';

const HEADER = [
  '-- Generated by RML Lean exporter.',
  '-- Supported subset: typed declarations, Pi/lambda/apply terms, and inductive declarations.',
  '',
];

const RESERVED = new Set([
  'Type', 'Prop', 'Sort',
  'axiom', 'def', 'fun', 'inductive', 'where',
  'match', 'with', 'let', 'in', 'if', 'then', 'else',
  'forall', 'by', 'theorem', 'example', 'namespace', 'open', 'import',
  'true', 'false',
]);

const PROBABILISTIC_HEADS = new Set([
  'range', 'valence', '=', '!=', 'and', 'or', 'not', 'both', 'neither',
]);

function leanIdent(raw) {
  if (raw === '_') return '_';
  let out = String(raw).replace(/[^A-Za-z0-9_]/g, '_');
  if (!out) out = 'rml';
  if (!/^[A-Za-z_]/.test(out)) out = `rml_${out}`;
  if (RESERVED.has(out)) out = `rml_${out}`;
  return out;
}

function withScope(scope, from, to) {
  const next = new Map(scope);
  next.set(from, to);
  return next;
}

function resolveName(name, scope) {
  if (scope.has(name)) return scope.get(name);
  if (name === 'Type' || name === 'Prop') return name;
  return leanIdent(name);
}

function unsupported(message, span) {
  throw new RmlError('E050', message, span);
}

function unwrapForm(form) {
  while (Array.isArray(form) && form.length === 1 && Array.isArray(form[0])) {
    form = form[0];
  }
  return form;
}

function cloneNode(node) {
  return Array.isArray(node) ? node.map(cloneNode) : node;
}

function substNode(node, name, replacement) {
  if (typeof node === 'string') return node === name ? cloneNode(replacement) : node;
  if (!Array.isArray(node)) return node;
  return node.map(child => substNode(child, name, replacement));
}

function wrapLean(expr) {
  if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(expr)) return expr;
  if (/^-?(\d+(\.\d+)?|\.\d+)$/.test(expr)) return expr;
  if (expr.startsWith('(') && expr.endsWith(')')) return expr;
  return `(${expr})`;
}

function typeToLean(node, ctx, scope, span) {
  if (typeof node === 'string') {
    if (isNum(node)) unsupported(`Lean export cannot use numeric literal \`${node}\` as a type`, span);
    return resolveName(node, scope);
  }
  if (!Array.isArray(node) || node.length === 0) {
    unsupported(`Lean export cannot translate malformed type \`${keyOf(node)}\``, span);
  }
  if (node.length === 2 && node[0] === 'Type' && typeof node[1] === 'string') {
    if (!/^(0|[1-9]\d*)$/.test(node[1])) {
      unsupported(`Lean export requires numeric Type levels, got \`${keyOf(node)}\``, span);
    }
    return `Type ${node[1]}`;
  }
  if (node.length === 1 && node[0] === 'Prop') return 'Prop';
  if (node.length === 3 && (node[0] === 'Pi' || node[0] === 'forall')) {
    const binding = parseBinding(node[1]);
    if (!binding) unsupported(`Lean export cannot translate malformed binder in \`${keyOf(node)}\``, span);
    const domain = typeToLean(binding.paramType, ctx, scope, span);
    const param = leanIdent(binding.paramName);
    const nextScope = binding.paramName === '_' ? scope : withScope(scope, binding.paramName, param);
    const codomain = typeToLean(node[2], ctx, nextScope, span);
    if (binding.paramName === '_') return `${wrapLean(domain)} -> ${codomain}`;
    return `(${param} : ${domain}) -> ${codomain}`;
  }
  return termToLean(node, ctx, scope, span);
}

function termToLean(node, ctx, scope, span) {
  if (typeof node === 'string') {
    if (isNum(node)) return node;
    return resolveName(node, scope);
  }
  if (!Array.isArray(node) || node.length === 0) {
    unsupported(`Lean export cannot translate malformed term \`${keyOf(node)}\``, span);
  }
  if (node.length === 4 && node[1] === 'has' && node[2] === 'probability') {
    unsupported('Lean export does not support probabilistic `has probability` forms', span);
  }
  if (node.length === 2 && node[0] === 'Type') return typeToLean(node, ctx, scope, span);
  if (node.length === 1 && node[0] === 'Prop') return 'Prop';
  if (node.length === 3 && (node[0] === 'Pi' || node[0] === 'forall')) {
    return typeToLean(node, ctx, scope, span);
  }
  if (node.length === 3 && node[0] === 'lambda') {
    const binding = parseBinding(node[1]);
    if (!binding) unsupported(`Lean export cannot translate malformed lambda binder in \`${keyOf(node)}\``, span);
    const param = leanIdent(binding.paramName);
    const domain = typeToLean(binding.paramType, ctx, scope, span);
    const nextScope = withScope(scope, binding.paramName, param);
    return `fun (${param} : ${domain}) => ${termToLean(node[2], ctx, nextScope, span)}`;
  }
  if (node.length === 3 && node[0] === 'apply') {
    const fn = termToLean(node[1], ctx, scope, span);
    const arg = termToLean(node[2], ctx, scope, span);
    return `${wrapLean(fn)} ${wrapLean(arg)}`;
  }
  if (node.length === 3 && node[1] === '=') {
    return `${wrapLean(termToLean(node[0], ctx, scope, span))} = ${wrapLean(termToLean(node[2], ctx, scope, span))}`;
  }
  if (node.length === 3 && node[1] === '!=') {
    return `${wrapLean(termToLean(node[0], ctx, scope, span))} != ${wrapLean(termToLean(node[2], ctx, scope, span))}`;
  }
  const [head, ...args] = node;
  if (typeof head !== 'string') {
    unsupported(`Lean export requires prefix application heads to be symbols, got \`${keyOf(node)}\``, span);
  }
  if (PROBABILISTIC_HEADS.has(head)) {
    unsupported(`Lean export does not support probabilistic operator \`${head}\``, span);
  }
  const fn = resolveName(head, scope);
  if (args.length === 0) return fn;
  return [fn, ...args.map(arg => wrapLean(termToLean(arg, ctx, scope, span)))].join(' ');
}

function inferType(node, ctx, bindings = new Map()) {
  if (typeof node === 'string') {
    if (bindings.has(node)) return bindings.get(node);
    return ctx.types.get(node) || null;
  }
  if (!Array.isArray(node) || node.length === 0) return null;
  if (node.length === 3 && node[0] === 'lambda') {
    const binding = parseBinding(node[1]);
    if (!binding) return null;
    const next = new Map(bindings);
    next.set(binding.paramName, binding.paramType);
    const bodyType = inferType(node[2], ctx, next);
    if (!bodyType) return null;
    return ['Pi', cloneNode(node[1]), bodyType];
  }
  if (node.length === 3 && node[0] === 'apply') {
    const fnType = inferType(node[1], ctx, bindings);
    if (Array.isArray(fnType) && fnType.length === 3 && fnType[0] === 'Pi') {
      const binding = parseBinding(fnType[1]);
      if (!binding) return null;
      return substNode(fnType[2], binding.paramName, node[2]);
    }
    return null;
  }
  const [head, ...args] = node;
  if (typeof head === 'string' && args.length > 0) {
    let current = ctx.types.get(head) || null;
    for (const arg of args) {
      if (!Array.isArray(current) || current.length !== 3 || current[0] !== 'Pi') return null;
      const binding = parseBinding(current[1]);
      if (!binding) return null;
      current = substNode(current[2], binding.paramName, arg);
    }
    return current;
  }
  return null;
}

function declareType(ctx, name, typeNode) {
  ctx.types.set(name, cloneNode(typeNode));
}

function exportDefinition(form, ctx, span) {
  const head = form[0].slice(0, -1);
  const rhs = form.slice(1);

  if (head === 'range' || head === 'valence') {
    unsupported(`Lean export does not support probabilistic configuration \`${head}:\``, span);
  }
  if (PROBABILISTIC_HEADS.has(head)) {
    unsupported(`Lean export does not support probabilistic operator definition \`${head}:\``, span);
  }

  // Untyped term declarations do not carry enough information for Lean; they
  // are accepted as context-only declarations and produce no artifact line.
  if (
    rhs.length === 3 &&
    typeof rhs[0] === 'string' &&
    rhs[1] === 'is' &&
    typeof rhs[2] === 'string' &&
    rhs[0] === head &&
    rhs[2] === head
  ) {
    return;
  }

  if (rhs.length === 2 && rhs[1] === head) {
    const typeNode = rhs[0];
    declareType(ctx, head, typeNode);
    ctx.lines.push(`axiom ${leanIdent(head)} : ${typeToLean(typeNode, ctx, new Map(), span)}`);
    return;
  }

  if (rhs.length === 1 && Array.isArray(rhs[0])) {
    const typeNode = rhs[0];
    declareType(ctx, head, typeNode);
    ctx.lines.push(`axiom ${leanIdent(head)} : ${typeToLean(typeNode, ctx, new Map(), span)}`);
    return;
  }

  if (rhs.length === 3 && rhs[0] === 'lambda' && Array.isArray(rhs[1])) {
    const lambdaNode = ['lambda', rhs[1], rhs[2]];
    const binding = parseBinding(rhs[1]);
    if (!binding) unsupported(`Lean export cannot translate malformed lambda binder in \`${keyOf(form)}\``, span);
    const typeNode = inferType(lambdaNode, ctx);
    if (!typeNode) unsupported(`Lean export could not infer a Lean type for \`${head}\``, span);
    declareType(ctx, head, typeNode);
    const param = leanIdent(binding.paramName);
    const scope = withScope(new Map(), binding.paramName, param);
    ctx.lines.push(
      `def ${leanIdent(head)} : ${typeToLean(typeNode, ctx, new Map(), span)} := ` +
      `fun ${param} => ${termToLean(rhs[2], ctx, scope, span)}`,
    );
    return;
  }

  unsupported(`Lean export supports typed declarations and lambda definitions, got \`${keyOf(form)}\``, span);
}

function constructorTypeToLean(ctorType, ctx, scope, span) {
  return typeToLean(ctorType, ctx, scope, span);
}

function exportInductive(form, ctx, span) {
  if (form.length < 3 || typeof form[1] !== 'string') {
    unsupported('Lean export requires `(inductive Name (constructor ...) ...)`', span);
  }
  const typeName = form[1];
  declareType(ctx, typeName, ['Type', '0']);
  const lines = [`inductive ${leanIdent(typeName)} : Type 0 where`];
  for (let i = 2; i < form.length; i++) {
    const clause = form[i];
    if (!Array.isArray(clause) || clause.length !== 2 || clause[0] !== 'constructor') {
      unsupported(`Lean export cannot translate malformed constructor clause \`${keyOf(clause)}\``, span);
    }
    const body = clause[1];
    if (typeof body === 'string') {
      declareType(ctx, body, typeName);
      lines.push(`  | ${leanIdent(body)} : ${leanIdent(typeName)}`);
      continue;
    }
    if (Array.isArray(body) && body.length === 2 && typeof body[0] === 'string') {
      const ctorName = body[0];
      const ctorType = body[1];
      declareType(ctx, ctorName, ctorType);
      lines.push(`  | ${leanIdent(ctorName)} : ${constructorTypeToLean(ctorType, ctx, new Map(), span)}`);
      continue;
    }
    unsupported(`Lean export cannot translate constructor clause \`${keyOf(clause)}\``, span);
  }
  ctx.blocks.push(lines.join('\n'));
}

function exportForm(form, ctx, span) {
  form = unwrapForm(form);
  if (!Array.isArray(form) || form.length === 0) {
    unsupported(`Lean export cannot translate top-level form \`${keyOf(form)}\``, span);
  }
  if (form.length === 4 && form[1] === 'has' && form[2] === 'probability') {
    unsupported('Lean export does not support probabilistic `has probability` forms', span);
  }
  if (form[0] === '?') return;
  if (form[0] === 'Type' || form[0] === 'Prop') return;
  if (typeof form[0] === 'string' && form[0].endsWith(':')) {
    exportDefinition(form, ctx, span);
    return;
  }
  if (form[0] === 'inductive') {
    exportInductive(form, ctx, span);
    return;
  }
  if (['namespace', 'import', 'template'].includes(form[0])) {
    unsupported(`Lean export does not yet support \`${form[0]}\` forms`, span);
  }
  unsupported(`Lean export supports typed declarations and inductives, got \`${keyOf(form)}\``, span);
}

function exportLean(text, options = {}) {
  const sourceText = String(text);
  const file = options.file || null;
  let forms;
  let spans;
  try {
    ({ forms, spans } = readLinoForms(sourceText, file));
  } catch (err) {
    const diag = new Diagnostic({
      code: (err && err.code) || 'E000',
      message: err && err.message ? err.message : String(err),
      span: (err && err.span) || { file, line: 1, col: 1, length: 0 },
    });
    return { source: '', diagnostics: [diag] };
  }

  const ctx = {
    types: new Map(),
    lines: [],
    blocks: [],
    diagnostics: [],
  };

  for (let idx = 0; idx < forms.length; idx++) {
    const span = spans[idx];
    try {
      exportForm(forms[idx], ctx, span);
    } catch (err) {
      ctx.diagnostics.push(new Diagnostic({
        code: (err && err.code) || 'E050',
        message: err && err.message ? err.message : String(err),
        span: (err && err.span) || span,
      }));
    }
  }

  if (ctx.diagnostics.length > 0) {
    return { source: '', diagnostics: ctx.diagnostics };
  }

  const chunks = [...HEADER];
  if (ctx.lines.length > 0) chunks.push(ctx.lines.join('\n'));
  if (ctx.lines.length > 0 && ctx.blocks.length > 0) chunks.push('');
  if (ctx.blocks.length > 0) chunks.push(ctx.blocks.join('\n\n'));
  return { source: chunks.join('\n').replace(/\n+$/u, '') + '\n', diagnostics: [] };
}

export { exportLean, leanIdent };
