//! Lean 4 exporter for the typed RML fragment (issue #60).
//!
//! The exporter translates declaration syntax into a Lean-checkable artifact
//! and rejects probabilistic forms instead of assigning them a Lean meaning.

use crate::{is_num, key_of, read_lino_forms, Diagnostic, Node, Span};
use std::collections::{HashMap, HashSet};

const HEADER: &[&str] = &[
    "-- Generated by RML Lean exporter.",
    "-- Supported subset: typed declarations, Pi/lambda/apply terms, and inductive declarations.",
    "",
];

/// Structured result returned by [`export_lean`].
#[derive(Debug, Clone)]
pub struct LeanExportResult {
    pub source: String,
    pub diagnostics: Vec<Diagnostic>,
}

#[derive(Debug, Clone)]
struct Binding {
    param_name: String,
    param_type: Node,
}

#[derive(Debug, Default)]
struct ExportCtx {
    types: HashMap<String, Node>,
    lines: Vec<String>,
    blocks: Vec<String>,
}

/// Convert an RML identifier to a Lean-safe identifier.
pub fn lean_ident(raw: &str) -> String {
    if raw == "_" {
        return "_".to_string();
    }
    let mut out: String = raw
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    if out.is_empty() {
        out = "rml".to_string();
    }
    if !out
        .chars()
        .next()
        .map(|c| c.is_ascii_alphabetic() || c == '_')
        .unwrap_or(false)
    {
        out = format!("rml_{}", out);
    }
    if reserved().contains(out.as_str()) {
        out = format!("rml_{}", out);
    }
    out
}

fn reserved() -> HashSet<&'static str> {
    [
        "Type",
        "Prop",
        "Sort",
        "axiom",
        "def",
        "fun",
        "inductive",
        "where",
        "match",
        "with",
        "let",
        "in",
        "if",
        "then",
        "else",
        "forall",
        "by",
        "theorem",
        "example",
        "namespace",
        "open",
        "import",
        "true",
        "false",
    ]
    .into_iter()
    .collect()
}

fn probabilistic_heads() -> HashSet<&'static str> {
    [
        "range", "valence", "=", "!=", "and", "or", "not", "both", "neither",
    ]
    .into_iter()
    .collect()
}

fn diagnostic(message: impl Into<String>, span: &Span) -> Diagnostic {
    Diagnostic::new("E050", message, span.clone())
}

fn unwrap_form(mut form: Node) -> Node {
    loop {
        match form {
            Node::List(children) if children.len() == 1 && matches!(children[0], Node::List(_)) => {
                form = children[0].clone();
            }
            _ => return form,
        }
    }
}

fn leaf(node: &Node) -> Option<&str> {
    match node {
        Node::Leaf(s) => Some(s),
        _ => None,
    }
}

fn list(node: &Node) -> Option<&[Node]> {
    match node {
        Node::List(children) => Some(children),
        _ => None,
    }
}

fn parse_binding_node(binding: &Node) -> Option<Binding> {
    let children = list(binding)?;
    if children.len() != 2 {
        return None;
    }
    if let Some(s) = leaf(&children[0]) {
        if let Some(name) = s.strip_suffix(':') {
            return Some(Binding {
                param_name: name.to_string(),
                param_type: children[1].clone(),
            });
        }
    }
    if let (Some(type_name), Some(var_name)) = (leaf(&children[0]), leaf(&children[1])) {
        if type_name
            .chars()
            .next()
            .map(|c| c.is_uppercase())
            .unwrap_or(false)
            && !var_name.ends_with(':')
        {
            return Some(Binding {
                param_name: var_name.to_string(),
                param_type: Node::Leaf(type_name.to_string()),
            });
        }
    }
    if matches!(children[0], Node::List(_)) {
        if let Some(var_name) = leaf(&children[1]) {
            if !var_name.ends_with(':') {
                return Some(Binding {
                    param_name: var_name.to_string(),
                    param_type: children[0].clone(),
                });
            }
        }
    }
    None
}

fn subst_node(node: &Node, name: &str, replacement: &Node) -> Node {
    match node {
        Node::Leaf(s) if s == name => replacement.clone(),
        Node::Leaf(_) => node.clone(),
        Node::List(children) => Node::List(
            children
                .iter()
                .map(|child| subst_node(child, name, replacement))
                .collect(),
        ),
    }
}

fn is_simple_atom(expr: &str) -> bool {
    if is_num(expr) {
        return true;
    }
    let mut chars = expr.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first.is_ascii_alphabetic() || first == '_') {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn wrap_lean(expr: &str) -> String {
    if is_simple_atom(expr) || (expr.starts_with('(') && expr.ends_with(')')) {
        expr.to_string()
    } else {
        format!("({})", expr)
    }
}

fn with_scope(scope: &HashMap<String, String>, from: &str, to: &str) -> HashMap<String, String> {
    let mut next = scope.clone();
    next.insert(from.to_string(), to.to_string());
    next
}

fn resolve_name(name: &str, scope: &HashMap<String, String>) -> String {
    if let Some(mapped) = scope.get(name) {
        return mapped.clone();
    }
    if name == "Type" || name == "Prop" {
        return name.to_string();
    }
    lean_ident(name)
}

fn type_to_lean(
    node: &Node,
    ctx: &ExportCtx,
    scope: &HashMap<String, String>,
    span: &Span,
) -> Result<String, String> {
    match node {
        Node::Leaf(s) => {
            if is_num(s) {
                return Err(format!(
                    "Lean export cannot use numeric literal `{}` as a type",
                    s
                ));
            }
            Ok(resolve_name(s, scope))
        }
        Node::List(children) => {
            if children.is_empty() {
                return Err(format!(
                    "Lean export cannot translate malformed type `{}`",
                    key_of(node)
                ));
            }
            if children.len() == 2 && leaf(&children[0]) == Some("Type") {
                if let Some(level) = leaf(&children[1]) {
                    if level.chars().all(|c| c.is_ascii_digit()) {
                        return Ok(format!("Type {}", level));
                    }
                }
                return Err(format!(
                    "Lean export requires numeric Type levels, got `{}`",
                    key_of(node)
                ));
            }
            if children.len() == 1 && leaf(&children[0]) == Some("Prop") {
                return Ok("Prop".to_string());
            }
            if children.len() == 3
                && (leaf(&children[0]) == Some("Pi") || leaf(&children[0]) == Some("forall"))
            {
                let binding = parse_binding_node(&children[1]).ok_or_else(|| {
                    format!(
                        "Lean export cannot translate malformed binder in `{}`",
                        key_of(node)
                    )
                })?;
                let domain = type_to_lean(&binding.param_type, ctx, scope, span)?;
                let param = lean_ident(&binding.param_name);
                let next_scope = if binding.param_name == "_" {
                    scope.clone()
                } else {
                    with_scope(scope, &binding.param_name, &param)
                };
                let codomain = type_to_lean(&children[2], ctx, &next_scope, span)?;
                if binding.param_name == "_" {
                    Ok(format!("{} -> {}", wrap_lean(&domain), codomain))
                } else {
                    Ok(format!("({} : {}) -> {}", param, domain, codomain))
                }
            } else {
                term_to_lean(node, ctx, scope, span)
            }
        }
    }
}

fn term_to_lean(
    node: &Node,
    ctx: &ExportCtx,
    scope: &HashMap<String, String>,
    span: &Span,
) -> Result<String, String> {
    match node {
        Node::Leaf(s) => {
            if is_num(s) {
                Ok(s.clone())
            } else {
                Ok(resolve_name(s, scope))
            }
        }
        Node::List(children) => {
            if children.is_empty() {
                return Err(format!(
                    "Lean export cannot translate malformed term `{}`",
                    key_of(node)
                ));
            }
            if children.len() == 4
                && leaf(&children[1]) == Some("has")
                && leaf(&children[2]) == Some("probability")
            {
                return Err(
                    "Lean export does not support probabilistic `has probability` forms"
                        .to_string(),
                );
            }
            if children.len() == 2 && leaf(&children[0]) == Some("Type") {
                return type_to_lean(node, ctx, scope, span);
            }
            if children.len() == 1 && leaf(&children[0]) == Some("Prop") {
                return Ok("Prop".to_string());
            }
            if children.len() == 3
                && (leaf(&children[0]) == Some("Pi") || leaf(&children[0]) == Some("forall"))
            {
                return type_to_lean(node, ctx, scope, span);
            }
            if children.len() == 3 && leaf(&children[0]) == Some("lambda") {
                let binding = parse_binding_node(&children[1]).ok_or_else(|| {
                    format!(
                        "Lean export cannot translate malformed lambda binder in `{}`",
                        key_of(node)
                    )
                })?;
                let param = lean_ident(&binding.param_name);
                let domain = type_to_lean(&binding.param_type, ctx, scope, span)?;
                let next_scope = with_scope(scope, &binding.param_name, &param);
                return Ok(format!(
                    "fun ({} : {}) => {}",
                    param,
                    domain,
                    term_to_lean(&children[2], ctx, &next_scope, span)?
                ));
            }
            if children.len() == 3 && leaf(&children[0]) == Some("apply") {
                let f = term_to_lean(&children[1], ctx, scope, span)?;
                let arg = term_to_lean(&children[2], ctx, scope, span)?;
                return Ok(format!("{} {}", wrap_lean(&f), wrap_lean(&arg)));
            }
            if children.len() == 3 && leaf(&children[1]) == Some("=") {
                let left = term_to_lean(&children[0], ctx, scope, span)?;
                let right = term_to_lean(&children[2], ctx, scope, span)?;
                return Ok(format!("{} = {}", wrap_lean(&left), wrap_lean(&right)));
            }
            if children.len() == 3 && leaf(&children[1]) == Some("!=") {
                let left = term_to_lean(&children[0], ctx, scope, span)?;
                let right = term_to_lean(&children[2], ctx, scope, span)?;
                return Ok(format!("{} != {}", wrap_lean(&left), wrap_lean(&right)));
            }
            let Some(head) = leaf(&children[0]) else {
                return Err(format!(
                    "Lean export requires prefix application heads to be symbols, got `{}`",
                    key_of(node)
                ));
            };
            if probabilistic_heads().contains(head) {
                return Err(format!(
                    "Lean export does not support probabilistic operator `{}`",
                    head
                ));
            }
            let f = resolve_name(head, scope);
            if children.len() == 1 {
                return Ok(f);
            }
            let mut parts = vec![f];
            for arg in &children[1..] {
                parts.push(wrap_lean(&term_to_lean(arg, ctx, scope, span)?));
            }
            Ok(parts.join(" "))
        }
    }
}

fn infer_type(node: &Node, ctx: &ExportCtx, bindings: &HashMap<String, Node>) -> Option<Node> {
    match node {
        Node::Leaf(s) => bindings
            .get(s)
            .cloned()
            .or_else(|| ctx.types.get(s).cloned()),
        Node::List(children) if children.len() == 3 && leaf(&children[0]) == Some("lambda") => {
            let binding = parse_binding_node(&children[1])?;
            let mut next = bindings.clone();
            next.insert(binding.param_name, binding.param_type.clone());
            let body_type = infer_type(&children[2], ctx, &next)?;
            Some(Node::List(vec![
                Node::Leaf("Pi".to_string()),
                children[1].clone(),
                body_type,
            ]))
        }
        Node::List(children) if children.len() == 3 && leaf(&children[0]) == Some("apply") => {
            let fn_type = infer_type(&children[1], ctx, bindings)?;
            let fn_children = list(&fn_type)?;
            if fn_children.len() != 3 || leaf(&fn_children[0]) != Some("Pi") {
                return None;
            }
            let binding = parse_binding_node(&fn_children[1])?;
            Some(subst_node(
                &fn_children[2],
                &binding.param_name,
                &children[2],
            ))
        }
        Node::List(children) if !children.is_empty() => {
            let head = leaf(&children[0])?;
            let mut current = ctx.types.get(head)?.clone();
            for arg in &children[1..] {
                let current_children = list(&current)?;
                if current_children.len() != 3 || leaf(&current_children[0]) != Some("Pi") {
                    return None;
                }
                let binding = parse_binding_node(&current_children[1])?;
                current = subst_node(&current_children[2], &binding.param_name, arg);
            }
            Some(current)
        }
        _ => None,
    }
}

fn declare_type(ctx: &mut ExportCtx, name: &str, typ: Node) {
    ctx.types.insert(name.to_string(), typ);
}

fn export_definition(form: &[Node], ctx: &mut ExportCtx, span: &Span) -> Result<(), String> {
    let Some(raw_head) = leaf(&form[0]) else {
        return Err(format!(
            "Lean export supports typed declarations, got `{}`",
            key_of(&Node::List(form.to_vec()))
        ));
    };
    let head = raw_head.trim_end_matches(':');
    let rhs = &form[1..];
    if head == "range" || head == "valence" {
        return Err(format!(
            "Lean export does not support probabilistic configuration `{}:`",
            head
        ));
    }
    if probabilistic_heads().contains(head) {
        return Err(format!(
            "Lean export does not support probabilistic operator definition `{}:`",
            head
        ));
    }

    if rhs.len() == 3
        && leaf(&rhs[0]) == Some(head)
        && leaf(&rhs[1]) == Some("is")
        && leaf(&rhs[2]) == Some(head)
    {
        return Ok(());
    }

    if rhs.len() == 2 && leaf(&rhs[1]) == Some(head) {
        let type_node = rhs[0].clone();
        declare_type(ctx, head, type_node.clone());
        ctx.lines.push(format!(
            "axiom {} : {}",
            lean_ident(head),
            type_to_lean(&type_node, ctx, &HashMap::new(), span)?
        ));
        return Ok(());
    }

    if rhs.len() == 1 && matches!(rhs[0], Node::List(_)) {
        let type_node = rhs[0].clone();
        declare_type(ctx, head, type_node.clone());
        ctx.lines.push(format!(
            "axiom {} : {}",
            lean_ident(head),
            type_to_lean(&type_node, ctx, &HashMap::new(), span)?
        ));
        return Ok(());
    }

    if rhs.len() == 3 && leaf(&rhs[0]) == Some("lambda") && matches!(rhs[1], Node::List(_)) {
        let lambda_node = Node::List(vec![
            Node::Leaf("lambda".to_string()),
            rhs[1].clone(),
            rhs[2].clone(),
        ]);
        let binding = parse_binding_node(&rhs[1]).ok_or_else(|| {
            format!(
                "Lean export cannot translate malformed lambda binder in `{}`",
                key_of(&Node::List(form.to_vec()))
            )
        })?;
        let type_node = infer_type(&lambda_node, ctx, &HashMap::new())
            .ok_or_else(|| format!("Lean export could not infer a Lean type for `{}`", head))?;
        declare_type(ctx, head, type_node.clone());
        let param = lean_ident(&binding.param_name);
        let scope = with_scope(&HashMap::new(), &binding.param_name, &param);
        ctx.lines.push(format!(
            "def {} : {} := fun {} => {}",
            lean_ident(head),
            type_to_lean(&type_node, ctx, &HashMap::new(), span)?,
            param,
            term_to_lean(&rhs[2], ctx, &scope, span)?
        ));
        return Ok(());
    }

    Err(format!(
        "Lean export supports typed declarations and lambda definitions, got `{}`",
        key_of(&Node::List(form.to_vec()))
    ))
}

fn export_inductive(form: &[Node], ctx: &mut ExportCtx, span: &Span) -> Result<(), String> {
    if form.len() < 3 {
        return Err("Lean export requires `(inductive Name (constructor ...) ...)`".to_string());
    }
    let Some(type_name) = leaf(&form[1]) else {
        return Err("Lean export requires `(inductive Name (constructor ...) ...)`".to_string());
    };
    declare_type(
        ctx,
        type_name,
        Node::List(vec![
            Node::Leaf("Type".to_string()),
            Node::Leaf("0".to_string()),
        ]),
    );
    let mut lines = vec![format!(
        "inductive {} : Type 0 where",
        lean_ident(type_name)
    )];
    for clause in &form[2..] {
        let Some(parts) = list(clause) else {
            return Err(format!(
                "Lean export cannot translate malformed constructor clause `{}`",
                key_of(clause)
            ));
        };
        if parts.len() != 2 || leaf(&parts[0]) != Some("constructor") {
            return Err(format!(
                "Lean export cannot translate malformed constructor clause `{}`",
                key_of(clause)
            ));
        }
        if let Some(ctor_name) = leaf(&parts[1]) {
            declare_type(ctx, ctor_name, Node::Leaf(type_name.to_string()));
            lines.push(format!(
                "  | {} : {}",
                lean_ident(ctor_name),
                lean_ident(type_name)
            ));
            continue;
        }
        if let Some(body) = list(&parts[1]) {
            if body.len() == 2 {
                if let Some(ctor_name) = leaf(&body[0]) {
                    let ctor_type = body[1].clone();
                    declare_type(ctx, ctor_name, ctor_type.clone());
                    lines.push(format!(
                        "  | {} : {}",
                        lean_ident(ctor_name),
                        type_to_lean(&ctor_type, ctx, &HashMap::new(), span)?
                    ));
                    continue;
                }
            }
        }
        return Err(format!(
            "Lean export cannot translate constructor clause `{}`",
            key_of(clause)
        ));
    }
    ctx.blocks.push(lines.join("\n"));
    Ok(())
}

fn export_form(form: Node, ctx: &mut ExportCtx, span: &Span) -> Result<(), String> {
    let form = unwrap_form(form);
    let Some(children) = list(&form) else {
        return Err(format!(
            "Lean export cannot translate top-level form `{}`",
            key_of(&form)
        ));
    };
    if children.is_empty() {
        return Err(format!(
            "Lean export cannot translate top-level form `{}`",
            key_of(&form)
        ));
    }
    if children.len() == 4
        && leaf(&children[1]) == Some("has")
        && leaf(&children[2]) == Some("probability")
    {
        return Err(
            "Lean export does not support probabilistic `has probability` forms".to_string(),
        );
    }
    if leaf(&children[0]) == Some("?")
        || leaf(&children[0]) == Some("Type")
        || leaf(&children[0]) == Some("Prop")
    {
        return Ok(());
    }
    if let Some(head) = leaf(&children[0]) {
        if head.ends_with(':') {
            return export_definition(children, ctx, span);
        }
        if head == "inductive" {
            return export_inductive(children, ctx, span);
        }
        if head == "namespace" || head == "import" || head == "template" {
            return Err(format!("Lean export does not yet support `{}` forms", head));
        }
    }
    Err(format!(
        "Lean export supports typed declarations and inductives, got `{}`",
        key_of(&form)
    ))
}

/// Export the supported typed RML fragment to Lean 4 source.
pub fn export_lean(text: &str, file: Option<&str>) -> LeanExportResult {
    let forms = match read_lino_forms(text, file) {
        Ok(forms) => forms,
        Err(diagnostic) => {
            return LeanExportResult {
                source: String::new(),
                diagnostics: vec![diagnostic],
            };
        }
    };
    let mut ctx = ExportCtx::default();
    let mut diagnostics = Vec::new();
    for (form, span) in forms {
        if let Err(message) = export_form(form, &mut ctx, &span) {
            diagnostics.push(diagnostic(message, &span));
        }
    }
    if !diagnostics.is_empty() {
        return LeanExportResult {
            source: String::new(),
            diagnostics,
        };
    }
    let mut chunks: Vec<String> = HEADER.iter().map(|s| s.to_string()).collect();
    if !ctx.lines.is_empty() {
        chunks.push(ctx.lines.join("\n"));
    }
    if !ctx.lines.is_empty() && !ctx.blocks.is_empty() {
        chunks.push(String::new());
    }
    if !ctx.blocks.is_empty() {
        chunks.push(ctx.blocks.join("\n\n"));
    }
    let mut source = chunks.join("\n");
    while source.ends_with('\n') {
        source.pop();
    }
    source.push('\n');
    LeanExportResult {
        source,
        diagnostics: Vec::new(),
    }
}
