//! Rocq exporter for the typed LiNo fragment (issue #61).
//!
//! The exporter intentionally covers the subset that has a direct Rocq
//! counterpart: stratified universes, typed declarations, Pi/lambda/apply,
//! equality expressions, type queries, and simple inductive declarations.

use crate::{is_num, key_of, parse_inductive_form, parse_lino, read_lino_form, Node};
use std::collections::HashMap;
use std::error::Error;
use std::fmt;
use std::panic::{catch_unwind, AssertUnwindSafe};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RocqExportError {
    message: String,
}

impl RocqExportError {
    fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}

impl fmt::Display for RocqExportError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.message)
    }
}

impl Error for RocqExportError {}

#[derive(Debug, Clone)]
struct Binding {
    name: String,
    typ: Node,
}

struct RocqEmitter {
    names: HashMap<String, String>,
    used: HashMap<String, String>,
}

// Reads every form before any is translated, so both runtimes report the same
// first error whatever the forms go on to declare.
fn parse_forms(text: &str) -> Result<Vec<Node>, RocqExportError> {
    parse_lino(text)
        .map_err(|error| RocqExportError::new(error.to_string()))?
        .into_iter()
        .map(|link| {
            read_lino_form(&link)
                .map_err(|e| RocqExportError::new(format!("failed to parse `{}`: {}", link, e)))
        })
        .collect()
}

pub fn export_rocq(text: &str, source_path: Option<&str>) -> Result<String, RocqExportError> {
    let mut emitter = RocqEmitter::new();
    let mut lines = vec!["(* Generated by rml export rocq. *)".to_string()];
    if let Some(path) = source_path {
        lines.push(format!("(* Source: {} *)", sanitize_comment(path)));
    }
    lines.push(String::new());
    lines.push("Set Universe Polymorphism.".to_string());
    lines.push(String::new());

    for node in parse_forms(text)? {
        if let Some(statement) = emitter.translate_form(&node)? {
            lines.push(statement);
        }
    }
    lines.push(String::new());
    Ok(lines.join("\n"))
}

impl RocqEmitter {
    fn new() -> Self {
        Self {
            names: HashMap::new(),
            used: HashMap::new(),
        }
    }

    fn err<T>(&self, message: impl Into<String>) -> Result<T, RocqExportError> {
        Err(RocqExportError::new(message))
    }

    fn symbol(&mut self, raw: &str) -> Result<String, RocqExportError> {
        if raw == "_" {
            return Ok("_".to_string());
        }
        if let Some(rendered) = self.names.get(raw) {
            return Ok(rendered.clone());
        }
        let rendered = sanitize_identifier(raw);
        if let Some(previous) = self.used.get(&rendered) {
            if previous != raw {
                return self.err(format!(
                    "Rocq identifier collision: `{}` and `{}` both export as `{}`",
                    previous, raw, rendered
                ));
            }
        }
        self.names.insert(raw.to_string(), rendered.clone());
        self.used.insert(rendered.clone(), raw.to_string());
        Ok(rendered)
    }

    fn translate_type(&mut self, node: &Node) -> Result<String, RocqExportError> {
        match node {
            Node::Leaf(s) => {
                if s == "Type" {
                    return Ok("Type".to_string());
                }
                if s == "Prop" {
                    return Ok("Prop".to_string());
                }
                if is_num(s) {
                    return self.err(format!("numeric literal `{}` is not a Rocq type", s));
                }
                self.symbol(s)
            }
            Node::List(children) => {
                if let Some(level) = type_universe_level(node) {
                    return Ok(if level == "0" { "Set" } else { "Type" }.to_string());
                }
                if children.len() == 1 && leaf_eq(&children[0], "Prop") {
                    return Ok("Prop".to_string());
                }
                if children.len() == 3
                    && (leaf_eq(&children[0], "Pi") || leaf_eq(&children[0], "forall"))
                {
                    return self.translate_pi(node);
                }
                if children.len() == 3 && leaf_eq(&children[1], "=") {
                    return Ok(format!(
                        "{} = {}",
                        self.translate_term(&children[0])?,
                        self.translate_term(&children[2])?
                    ));
                }
                self.translate_term(node)
            }
        }
    }

    fn translate_pi(&mut self, node: &Node) -> Result<String, RocqExportError> {
        let mut current = node;
        let mut binders: Vec<Binding> = Vec::new();
        loop {
            let Node::List(children) = current else {
                break;
            };
            if children.len() != 3
                || !(leaf_eq(&children[0], "Pi") || leaf_eq(&children[0], "forall"))
            {
                break;
            }
            let binding = parse_binding_node(&children[1]).ok_or_else(|| {
                RocqExportError::new(format!("unsupported Pi binder `{}`", key_of(&children[1])))
            })?;
            binders.push(binding);
            current = &children[2];
        }

        let mut rendered = self.translate_type(current)?;
        for binding in binders.iter().rev() {
            rendered = format!(
                "forall {} : {}, {}",
                self.symbol(&binding.name)?,
                self.translate_type(&binding.typ)?,
                rendered
            );
        }
        Ok(rendered)
    }

    fn translate_lambda(&mut self, node: &Node) -> Result<String, RocqExportError> {
        let Node::List(children) = node else {
            return self.err(format!("unsupported lambda expression `{}`", key_of(node)));
        };
        if children.len() != 3 || !leaf_eq(&children[0], "lambda") {
            return self.err(format!("unsupported lambda expression `{}`", key_of(node)));
        }
        let bindings = parse_binding_nodes(&children[1]).ok_or_else(|| {
            RocqExportError::new(format!(
                "unsupported lambda binder `{}`",
                key_of(&children[1])
            ))
        })?;
        if bindings.is_empty() {
            return self.err(format!(
                "unsupported lambda binder `{}`",
                key_of(&children[1])
            ));
        }

        let mut rendered = self.translate_term(&children[2])?;
        for binding in bindings.iter().rev() {
            rendered = format!(
                "fun {} : {} => {}",
                self.symbol(&binding.name)?,
                self.translate_type(&binding.typ)?,
                rendered
            );
        }
        Ok(rendered)
    }

    fn translate_term(&mut self, node: &Node) -> Result<String, RocqExportError> {
        match node {
            Node::Leaf(s) => {
                if is_num(s) {
                    return self.err(format!(
                        "numeric literal `{}` is outside the Rocq export subset",
                        s
                    ));
                }
                self.symbol(s)
            }
            Node::List(children) => {
                if children.is_empty() {
                    return self.err(format!(
                        "unsupported Rocq term expression `{}`",
                        key_of(node)
                    ));
                }
                if type_universe_level(node).is_some() {
                    return self.translate_type(node);
                }
                if children.len() == 1 && leaf_eq(&children[0], "Prop") {
                    return Ok("Prop".to_string());
                }
                if children.len() == 3 && leaf_eq(&children[0], "lambda") {
                    return self.translate_lambda(node);
                }
                if children.len() == 3
                    && (leaf_eq(&children[0], "Pi") || leaf_eq(&children[0], "forall"))
                {
                    return self.translate_pi(node);
                }
                if children.len() == 3 && leaf_eq(&children[1], "=") {
                    return Ok(format!(
                        "({} = {})",
                        self.translate_term(&children[0])?,
                        self.translate_term(&children[2])?
                    ));
                }
                if children.len() == 3 && leaf_eq(&children[1], "of") {
                    return Ok(format!(
                        "({} : {})",
                        self.translate_term(&children[0])?,
                        self.translate_type(&children[2])?
                    ));
                }
                if leaf_eq(&children[0], "apply") {
                    if children.len() != 3 {
                        return self.err(format!(
                            "Rocq export supports binary `apply` forms, got `{}`",
                            key_of(node)
                        ));
                    }
                    return Ok(format!(
                        "({} {})",
                        self.translate_term(&children[1])?,
                        self.translate_term(&children[2])?
                    ));
                }
                let Some(head) = leaf(&children[0]) else {
                    return self.err(format!(
                        "unsupported Rocq term expression `{}`",
                        key_of(node)
                    ));
                };
                if unsupported_form_head(head) {
                    return self.err(format!("`{}` is outside the Rocq export subset", head));
                }
                if matches!(
                    head,
                    "+" | "-" | "*" | "/" | "and" | "or" | "not" | "both" | "neither"
                ) {
                    return self.err(format!(
                        "operator `{}` is outside the Rocq export subset",
                        head
                    ));
                }
                let mut parts = vec![self.symbol(head)?];
                for arg in &children[1..] {
                    parts.push(self.translate_term(arg)?);
                }
                Ok(format!("({})", parts.join(" ")))
            }
        }
    }

    fn translate_query(&mut self, node: &Node) -> Result<String, RocqExportError> {
        let Node::List(children) = node else {
            return self.err(format!("unsupported query form `{}`", key_of(node)));
        };
        if children.len() == 4 {
            return self.err("proof-producing queries are outside the Rocq export subset");
        }
        if children.len() != 2 || !leaf_eq(&children[0], "?") {
            return self.err(format!("unsupported query form `{}`", key_of(node)));
        }
        let expr = &children[1];
        if let Node::List(items) = expr {
            if items.len() == 3 && leaf_eq(&items[0], "type") && leaf_eq(&items[1], "of") {
                return Ok(format!("Check {}.", self.translate_term(&items[2])?));
            }
            if items.len() == 3 && leaf_eq(&items[1], "of") {
                return Ok(format!(
                    "Check ({} : {}).",
                    self.translate_term(&items[0])?,
                    self.translate_type(&items[2])?
                ));
            }
        }
        Ok(format!("Check {}.", self.translate_term(expr)?))
    }

    fn translate_definition(
        &mut self,
        node: &Node,
        children: &[Node],
    ) -> Result<String, RocqExportError> {
        let Some(head_with_colon) = leaf(&children[0]) else {
            return self.err(format!(
                "definition `{}` is outside the Rocq export subset",
                key_of(node)
            ));
        };
        let head = head_with_colon.trim_end_matches(':');
        let rhs = &children[1..];
        if head == "Type" {
            return self.err("self-referential `(Type: Type Type)` is not in the Rocq export subset; use `(Type N)` universes");
        }
        if config_head(head) || operator_head(head) || head.contains('=') || head.contains('!') {
            return self.err(format!(
                "definition `{}:` is an operator or configuration form, not a typed Rocq declaration",
                head
            ));
        }
        if rhs.len() == 1 {
            if let Some(value) = leaf(&rhs[0]) {
                if is_num(value) {
                    return self.err(format!(
                        "numeric prior `({}: {})` is outside the Rocq export subset",
                        head, value
                    ));
                }
            }
        }
        if rhs.len() == 3 && leaf_eq(&rhs[1], "is") {
            return self.err(format!(
                "untyped term declaration `({}: ... is ...)` is outside the Rocq export subset",
                head
            ));
        }
        if !rhs.is_empty() && leaf_eq(&rhs[0], "lambda") {
            let mut lambda_items = vec![Node::Leaf("lambda".to_string())];
            lambda_items.extend_from_slice(&rhs[1..]);
            let lambda = Node::List(lambda_items);
            return Ok(format!(
                "Definition {} := {}.",
                self.symbol(head)?,
                self.translate_lambda(&lambda)?
            ));
        }
        if rhs.len() == 2 {
            if let Some(value) = leaf(&rhs[1]) {
                if value == head {
                    return Ok(format!(
                        "Parameter {} : {}.",
                        self.symbol(head)?,
                        self.translate_type(&rhs[0])?
                    ));
                }
            }
        }
        if rhs.len() == 1 && matches!(rhs[0], Node::List(_)) {
            return Ok(format!(
                "Parameter {} : {}.",
                self.symbol(head)?,
                self.translate_type(&rhs[0])?
            ));
        }
        self.err(format!(
            "definition `{}` is outside the Rocq export subset",
            key_of(node)
        ))
    }

    fn translate_inductive(&mut self, node: &Node) -> Result<String, RocqExportError> {
        let decl = catch_unwind(AssertUnwindSafe(|| parse_inductive_form(node)))
            .map_err(|payload| RocqExportError::new(panic_payload_message(payload)))?
            .ok_or_else(|| {
                RocqExportError::new(format!(
                    "unsupported inductive declaration `{}`",
                    key_of(node)
                ))
            })?;
        let mut lines = vec![format!("Inductive {} : Set :=", self.symbol(&decl.name)?)];
        for (i, ctor) in decl.constructors.iter().enumerate() {
            let suffix = if i + 1 == decl.constructors.len() {
                "."
            } else {
                ""
            };
            lines.push(format!(
                "| {} : {}{}",
                self.symbol(&ctor.name)?,
                self.translate_type(&ctor.typ)?,
                suffix
            ));
        }
        Ok(lines.join("\n"))
    }

    fn translate_form(&mut self, node: &Node) -> Result<Option<String>, RocqExportError> {
        let Node::List(children) = node else {
            return self.err(format!("unsupported top-level form `{}`", key_of(node)));
        };
        if children.is_empty() {
            return self.err(format!("unsupported top-level form `{}`", key_of(node)));
        }
        if leaf(&children[0]).is_some_and(|s| s.ends_with(':')) {
            return self.translate_definition(node, children).map(Some);
        }
        if type_universe_level(node).is_some()
            || (children.len() == 1 && leaf_eq(&children[0], "Prop"))
        {
            return Ok(None);
        }
        if children.len() == 4
            && leaf_eq(&children[1], "has")
            && leaf_eq(&children[2], "probability")
        {
            return self.err("probabilistic assignment is outside the Rocq export subset");
        }
        if leaf_eq(&children[0], "inductive") {
            return self.translate_inductive(node).map(Some);
        }
        if leaf_eq(&children[0], "?") {
            return self.translate_query(node).map(Some);
        }
        if let Some(head) = leaf(&children[0]) {
            if unsupported_form_head(head) {
                return self.err(format!("`{}` is outside the Rocq export subset", head));
            }
        }
        self.err(format!(
            "top-level form `{}` is outside the Rocq export subset",
            key_of(node)
        ))
    }
}

fn leaf(node: &Node) -> Option<&str> {
    match node {
        Node::Leaf(s) => Some(s.as_str()),
        Node::List(_) => None,
    }
}

fn leaf_eq(node: &Node, expected: &str) -> bool {
    leaf(node) == Some(expected)
}

fn parse_binding_node(binding: &Node) -> Option<Binding> {
    let Node::List(children) = binding else {
        return None;
    };
    if children.len() != 2 {
        return None;
    }
    if let Some(name) = leaf(&children[0]).and_then(|s| s.strip_suffix(':')) {
        return Some(Binding {
            name: name.to_string(),
            typ: children[1].clone(),
        });
    }
    if let (Some(type_name), Some(var_name)) = (leaf(&children[0]), leaf(&children[1])) {
        if type_name
            .chars()
            .next()
            .is_some_and(|c| c.is_ascii_uppercase())
            && !var_name.ends_with(':')
        {
            return Some(Binding {
                name: var_name.to_string(),
                typ: Node::Leaf(type_name.to_string()),
            });
        }
    }
    if matches!(children[0], Node::List(_)) {
        if let Some(var_name) = leaf(&children[1]) {
            if !var_name.ends_with(':') {
                return Some(Binding {
                    name: var_name.to_string(),
                    typ: children[0].clone(),
                });
            }
        }
    }
    None
}

fn parse_binding_nodes(binding: &Node) -> Option<Vec<Binding>> {
    if let Some(single) = parse_binding_node(binding) {
        return Some(vec![single]);
    }
    let Node::List(children) = binding else {
        return None;
    };
    let mut tokens = Vec::new();
    for child in children {
        let token = leaf(child)?;
        if let Some(stripped) = token.strip_suffix(',') {
            tokens.push(stripped.to_string());
            tokens.push(",".to_string());
        } else {
            tokens.push(token.to_string());
        }
    }
    let mut bindings = Vec::new();
    let mut i = 0;
    while i < tokens.len() {
        if tokens[i] == "," {
            i += 1;
            continue;
        }
        if i + 1 < tokens.len() && tokens[i + 1] != "," {
            let pair = Node::List(vec![
                Node::Leaf(tokens[i].clone()),
                Node::Leaf(tokens[i + 1].clone()),
            ]);
            if let Some(binding) = parse_binding_node(&pair) {
                bindings.push(binding);
                i += 2;
                continue;
            }
        }
        return None;
    }
    if bindings.is_empty() {
        None
    } else {
        Some(bindings)
    }
}

fn type_universe_level(node: &Node) -> Option<&str> {
    let Node::List(children) = node else {
        return None;
    };
    if children.len() != 2 || !leaf_eq(&children[0], "Type") {
        return None;
    }
    let level = leaf(&children[1])?;
    if level.is_empty() || !level.chars().all(|c| c.is_ascii_digit()) {
        return None;
    }
    if level.len() > 1 && level.starts_with('0') {
        return None;
    }
    Some(level)
}

fn sanitize_comment(text: &str) -> String {
    text.replace("*)", "* )")
}

fn sanitize_identifier(raw: &str) -> String {
    let mut out = String::new();
    let mut previous_underscore = false;
    for ch in raw.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            out.push(ch);
            previous_underscore = false;
        } else if !previous_underscore {
            out.push('_');
            previous_underscore = true;
        }
    }
    if out.is_empty()
        || !out
            .chars()
            .next()
            .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
    {
        out = format!("rml_{}", out);
    }
    if rocq_reserved(&out) {
        out.push_str("_rml");
    }
    out
}

fn rocq_reserved(value: &str) -> bool {
    matches!(
        value,
        "as" | "at"
            | "by"
            | "Check"
            | "Definition"
            | "else"
            | "end"
            | "fix"
            | "forall"
            | "fun"
            | "if"
            | "in"
            | "Inductive"
            | "let"
            | "match"
            | "Parameter"
            | "Prop"
            | "return"
            | "Set"
            | "struct"
            | "then"
            | "Type"
            | "where"
            | "with"
    )
}

fn config_head(head: &str) -> bool {
    matches!(head, "range" | "valence")
}

fn operator_head(head: &str) -> bool {
    matches!(
        head,
        "=" | "!=" | "and" | "or" | "not" | "is" | "?:" | "both" | "neither"
    )
}

fn unsupported_form_head(head: &str) -> bool {
    matches!(
        head,
        "coinductive"
            | "coverage"
            | "define"
            | "import"
            | "mode"
            | "namespace"
            | "relation"
            | "terminating"
            | "total"
            | "world"
    )
}

fn panic_payload_message(payload: Box<dyn std::any::Any + Send>) -> String {
    if let Some(message) = payload.downcast_ref::<&str>() {
        return (*message).to_string();
    }
    if let Some(message) = payload.downcast_ref::<String>() {
        return message.clone();
    }
    "invalid inductive declaration".to_string()
}
