//! Deterministic process harness. Hex JSON lines only carry the exact ABI frames;
//! all runtime input/output terms cross the generated byte-frame boundary.
use std::io::{self, BufRead, Write};
use rml::linked_program::{ExecutionBasis, LinkedProgramRegistry};
use rml_linked_target::{abi, parse_target_frame, replay_target_frame, verify_target_frame};
use serde_json::{json, Value};

fn bytes(value: &Value) -> Result<Vec<u8>, String> {
    let s = value.as_str().ok_or("expected hex frame")?;
    if s.len() % 2 != 0 || !s.is_ascii() { return Err("invalid hex frame".into()); }
    (0..s.len()).step_by(2).map(|i| u8::from_str_radix(&s[i..i+2],16).map_err(|_| "invalid hex frame".into())).collect()
}
fn hex(bytes: &[u8]) -> String { bytes.iter().map(|b| format!("{b:02x}")).collect() }
fn execute(registry: Option<&LinkedProgramRegistry>, request: &Value) -> Result<Value, String> {
    let frame = bytes(&request["frame"])?;
    let result = match request["op"].as_str().ok_or("operation required")? {
        "roundtrip" => abi::encode_frame(&abi::decode_frame(&frame)?)?,
        "parse" => parse_target_frame(&frame)?,
        "verify" => verify_target_frame(registry.ok_or("proof registry required")?, &frame, 100000)?,
        "exhaust" => verify_target_frame(registry.ok_or("proof registry required")?, &frame, 1)?,
        "replay" => replay_target_frame(registry.ok_or("proof registry required")?, &bytes(&request["context"] )?, &bytes(&request["goal"] )?, &frame, 100000)?,
        "quote" => abi::encode_frame(&abi::execute_program("quote", &[abi::decode_frame(&frame)?])?)?,
        _ => return Err("unknown operation".into()),
    };
    Ok(json!({"ok":true,"frame":hex(&result)}))
}
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let source = concat!(include_str!("../../../lib/meta-theory/universal.lino"), "\n", include_str!("../../../lib/meta-theory/proof-verifier.lino"));
    let mut registry = None;
    for line in io::stdin().lock().lines() {
        let result = serde_json::from_str::<Value>(&line?).map_err(|e| e.to_string()).and_then(|value| {
            if matches!(value["op"].as_str(), Some("verify" | "replay" | "exhaust")) && registry.is_none() {
                registry = Some(LinkedProgramRegistry::from_rml_with_basis(source, ExecutionBasis::DirectStructural, &[])?);
            }
            execute(registry.as_ref(), &value)
        });
        let answer = match result { Ok(value) => value, Err(error) => json!({"ok":false,"error":error}) };
        println!("{}", answer);
        io::stdout().flush()?;
    }
    Ok(())
}
