// Rocq exporter tests for issue #61.
//
// Mirrors js/tests/rocq-export.test.mjs so both implementations keep the
// same supported subset and emitted Rocq source.

use rml::rocq::export_rocq;
use std::fs;
use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

fn temp_dir(tag: &str) -> std::path::PathBuf {
    let mut d = std::env::temp_dir();
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    d.push(format!("rml-rocq-export-{}-{}", tag, nanos));
    fs::create_dir_all(&d).unwrap();
    d
}

#[test]
fn exports_typed_declarations_and_typed_queries() {
    let source = [
        "(Natural: (Type 0) Natural)",
        "(zero: Natural zero)",
        "(succ: (Pi (Natural n) Natural))",
        "(identity: lambda (Natural x) x)",
        "(? (zero of Natural))",
        "(? (type of zero))",
        "(? (apply succ zero))",
    ]
    .join("\n");

    assert_eq!(
        export_rocq(&source, None).unwrap(),
        [
            "(* Generated by rml export rocq. *)",
            "",
            "Set Universe Polymorphism.",
            "",
            "Parameter rml_ref_4e61747572616c : Set.",
            "Parameter rml_ref_7a65726f : rml_ref_4e61747572616c.",
            "Parameter rml_ref_73756363 : forall rml_ref_6e : rml_ref_4e61747572616c, rml_ref_4e61747572616c.",
            "Definition rml_ref_6964656e74697479 := fun rml_ref_78 : rml_ref_4e61747572616c => rml_ref_78.",
            "Check (rml_ref_7a65726f : rml_ref_4e61747572616c).",
            "Check rml_ref_7a65726f.",
            "Check (rml_ref_73756363 rml_ref_7a65726f).",
            "",
        ]
        .join("\n")
    );
}

#[test]
fn exports_simple_inductive_declarations() {
    let source = [
        "(inductive Natural",
        "  (constructor zero)",
        "  (constructor (succ (Pi (Natural n) Natural))))",
        "(? (succ zero))",
    ]
    .join("\n");

    assert_eq!(
        export_rocq(&source, None).unwrap(),
        [
            "(* Generated by rml export rocq. *)",
            "",
            "Set Universe Polymorphism.",
            "",
            "Inductive rml_ref_4e61747572616c : Set :=",
            "| rml_ref_7a65726f : rml_ref_4e61747572616c",
            "| rml_ref_73756363 : forall rml_ref_6e : rml_ref_4e61747572616c, rml_ref_4e61747572616c.",
            "Check (rml_ref_73756363 rml_ref_7a65726f).",
            "",
        ]
        .join("\n")
    );
}

#[test]
fn rejects_probabilistic_assignments() {
    let err = export_rocq("((p = true) has probability 1)", None).unwrap_err();
    assert!(err.to_string().contains("probabilistic assignment"));
}

#[test]
fn cli_writes_rocq_output_file() {
    let tmp = temp_dir("cli");
    let output = tmp.join("program.v");
    let input = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("examples")
        .join("rocq-export.lino");

    let exe = env!("CARGO_BIN_EXE_rml");
    let status = Command::new(exe)
        .arg("export")
        .arg("rocq")
        .arg(&input)
        .arg("-o")
        .arg(&output)
        .status()
        .unwrap();
    assert!(status.success());

    let source = fs::read_to_string(&input).unwrap();
    let expected = export_rocq(&source, Some(input.to_str().unwrap())).unwrap();
    assert_eq!(fs::read_to_string(output).unwrap(), expected);
}
