theory Isabelle_Typed_Fragment
  imports Main
begin

(* Generated by RML Isabelle exporter. *)

typedecl rml_natural
typedecl rml_boolean

datatype rml_tree =
  rml_leaf
  | rml_branch rml_tree rml_tree

consts
  rml_zero :: "rml_natural"
  rml_succ :: "rml_natural => rml_natural"

definition rml_identity :: "rml_natural => rml_natural" where
  "rml_identity = (%v_ref_78. v_ref_78)"

end
