-- Generated by RML Lean exporter.
-- Supported subset: typed declarations, Pi/lambda/apply terms, and inductive declarations.

axiom rml_ref_4e61747572616c : Type 0
axiom rml_ref_7a65726f : rml_ref_4e61747572616c
axiom rml_ref_73756363 : (rml_ref_6e : rml_ref_4e61747572616c) -> rml_ref_4e61747572616c
def rml_ref_6964656e74697479 : (rml_ref_78 : rml_ref_4e61747572616c) -> rml_ref_4e61747572616c := fun rml_ref_78 => rml_ref_78
noncomputable def rml_ref_7477696365 : (rml_ref_78 : rml_ref_4e61747572616c) -> rml_ref_4e61747572616c := fun rml_ref_78 => rml_ref_73756363 (rml_ref_73756363 rml_ref_78)

inductive rml_ref_5472757468 : Type 0 where
  | rml_ref_74727574682d66616c7365 : rml_ref_5472757468
  | rml_ref_74727574682d74727565 : rml_ref_5472757468
